# Generated by Django 2.2.6 on 2020-02-14 08:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('panda', '0006_auto_20200214_0744'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactUs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=None, max_length=100)),
                ('email', models.EmailField(default=None, max_length=150)),
                ('phone', models.FloatField(default=None, max_length=12)),
                ('query', models.TextField(default=None, max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default=None, max_length=100)),
                ('email', models.EmailField(blank=True, default=None, max_length=150)),
                ('description', models.TextField(max_length=750)),
                ('rating', models.IntegerField(blank=True, default=None)),
            ],
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=None, max_length=100)),
                ('email', models.EmailField(default=None, max_length=150)),
                ('phone', models.FloatField(default=None, max_length=12)),
                ('dateTime', models.DateTimeField()),
                ('status', models.CharField(choices=[('appointed', 'appointed'), ('unassigned', 'unassigned'), ('completed', 'completed')], default=('unassigned', 'unassigned'), max_length=50)),
                ('partner_associate', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='panda.Partners')),
            ],
        ),
    ]
