# Generated by Django 2.2.6 on 2020-05-15 10:36

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0002_auto_20200219_0804'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='partner_associate',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='panda.Partners'),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='rating',
            field=models.IntegerField(blank=True, default=None, validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(0)]),
        ),
    ]
