# Generated by Django 2.2.6 on 2020-05-15 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about_us', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviceaddress',
            name='address_type',
            field=models.CharField(choices=[('ho', 'Head Office'), ('ca', 'Chamber Addres'), ('oa', 'Other Offices')], default='address_choices[2]', max_length=20, null=True),
        ),
    ]
