# Generated by Django 2.2.6 on 2020-05-18 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about_us', '0002_auto_20200515_1606'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviceaddress',
            name='address_type',
            field=models.CharField(choices=[('Head Office', 'Head Office'), ('Chamber Addres', 'Chamber Addres'), ('Other Offices', 'Other Offices')], default='address_choices[2]', max_length=20, null=True),
        ),
    ]
