# Generated by Django 2.2.6 on 2020-02-14 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('human_resource', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employment_application',
            name='designation',
            field=models.CharField(blank=True, default=None, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='employment_application',
            name='email',
            field=models.EmailField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='employment_application',
            name='experience_years',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='employment_application',
            name='first_name',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='employment_application',
            name='last_name',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='employment_application',
            name='phone',
            field=models.FloatField(max_length=12, null=True),
        ),
        migrations.AddField(
            model_name='employment_application',
            name='resume',
            field=models.FileField(blank=True, null=True, upload_to='resume'),
        ),
    ]
