# Generated by Django 2.2.6 on 2020-02-14 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('writer', models.CharField(max_length=100)),
                ('content', models.CharField(max_length=20000)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField(blank=True, default=None)),
                ('description', models.TextField(default=models.CharField(max_length=200), max_length=1000)),
                ('street_address', models.CharField(blank=True, default=None, max_length=200)),
                ('city', models.CharField(blank=True, default=None, max_length=30)),
                ('state', models.CharField(blank=True, default=None, max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('heading', models.CharField(max_length=200)),
                ('sub_heading', models.CharField(blank=True, default=models.CharField(max_length=200), max_length=500)),
                ('content', models.TextField(max_length=10000)),
                ('source', models.CharField(blank=True, default=None, max_length=200)),
                ('publisher', models.CharField(default='Legacy Law', max_length=200)),
            ],
        ),
    ]
