# Generated by Django 2.2.6 on 2020-02-14 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bulletin', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='event_image',
            field=models.ImageField(blank='True', upload_to='events'),
        ),
        migrations.AddField(
            model_name='news',
            name='news_image',
            field=models.ImageField(blank='True', upload_to='news'),
        ),
    ]
