# Generated by Django 2.2.6 on 2020-02-14 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bulletin', '0004_auto_20200214_1007'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='end_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
