# Generated by Django 2.2.6 on 2020-02-12 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Partners',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('designation', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=20)),
                ('short_description', models.TextField(max_length=228)),
                ('long_description', models.TextField(max_length=1028)),
                ('llb_university', models.CharField(max_length=100)),
                ('llb_city', models.CharField(max_length=20)),
                ('mbl_university', models.CharField(max_length=100)),
                ('mbl_city', models.CharField(max_length=20)),
                ('bar_admition', models.DateField()),
                ('bar_membership_city', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=40)),
                ('address', models.CharField(max_length=40)),
                ('phone', models.CharField(max_length=40)),
                ('display_picture', models.ImageField(blank='True', upload_to='display_picture')),
            ],
        ),
    ]
