# Generated by Django 2.2.6 on 2020-02-12 07:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('panda', '0001_initial'),
    ]

    operations = [
    ]
