# Generated by Django 2.2.6 on 2020-02-12 07:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('panda', '0002_auto_20200212_0716'),
    ]

    operations = [
    ]
