# Generated by Django 2.2.6 on 2020-02-14 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panda', '0004_auto_20200212_0722'),
    ]

    operations = [
        migrations.CreateModel(
            name='PracticingArea',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default=None, max_length=50)),
                ('discription', models.TextField(default=None, max_length=10000)),
                ('specialization_1', models.CharField(default=None, max_length=100)),
                ('specialization_2', models.CharField(default=None, max_length=100)),
                ('specialization_3', models.CharField(default=None, max_length=100)),
                ('specialization_4', models.CharField(default=None, max_length=100)),
                ('specialization_5', models.CharField(default=None, max_length=100)),
                ('specialization_6', models.CharField(default=None, max_length=100)),
                ('specialization_7', models.CharField(default=None, max_length=100)),
                ('specialization_8', models.CharField(default=None, max_length=100)),
                ('specialization_9', models.CharField(default=None, max_length=100)),
                ('specialization_10', models.CharField(default=None, max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='partners',
            name='designation',
            field=models.CharField(choices=[('mp', 'Managing Partner'), ('sp', 'Senior Partner'), ('p', 'Partner'), ('pa', 'Principal Associate'), ('sa', 'Senior Associate'), ('a', 'Associate')], max_length=50),
        ),
    ]
