# Generated by Django 2.2.6 on 2020-02-14 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panda', '0005_auto_20200214_0738'),
    ]

    operations = [
        migrations.AlterField(
            model_name='practicingarea',
            name='specialization_1',
            field=models.CharField(blank=True, default=None, max_length=100),
        ),
        migrations.AlterField(
            model_name='practicingarea',
            name='specialization_10',
            field=models.CharField(blank=True, default=None, max_length=100),
        ),
        migrations.AlterField(
            model_name='practicingarea',
            name='specialization_2',
            field=models.CharField(blank=True, default=None, max_length=100),
        ),
        migrations.AlterField(
            model_name='practicingarea',
            name='specialization_3',
            field=models.CharField(blank=True, default=None, max_length=100),
        ),
        migrations.AlterField(
            model_name='practicingarea',
            name='specialization_4',
            field=models.CharField(blank=True, default=None, max_length=100),
        ),
        migrations.AlterField(
            model_name='practicingarea',
            name='specialization_5',
            field=models.CharField(blank=True, default=None, max_length=100),
        ),
        migrations.AlterField(
            model_name='practicingarea',
            name='specialization_6',
            field=models.CharField(blank=True, default=None, max_length=100),
        ),
        migrations.AlterField(
            model_name='practicingarea',
            name='specialization_7',
            field=models.CharField(blank=True, default=None, max_length=100),
        ),
        migrations.AlterField(
            model_name='practicingarea',
            name='specialization_8',
            field=models.CharField(blank=True, default=None, max_length=100),
        ),
        migrations.AlterField(
            model_name='practicingarea',
            name='specialization_9',
            field=models.CharField(blank=True, default=None, max_length=100),
        ),
    ]
