# Generated by Django 2.2.6 on 2020-02-26 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panda', '0006_auto_20200214_0744'),
    ]

    operations = [
        migrations.AddField(
            model_name='partners',
            name='slug',
            field=models.CharField(blank=True, default='<django.db.models.fields.CharField>-<django.db.models.fields.CharField>', max_length=60, null=True),
        ),
    ]
