# Generated by Django 2.2.6 on 2020-02-26 08:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('panda', '0007_partners_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='partners',
            name='slug',
        ),
    ]
