# Generated by Django 2.2.6 on 2020-02-26 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panda', '0008_remove_partners_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='partners',
            name='slug_field',
            field=models.SlugField(default='<django.db.models.fields.CharField>_<django.db.models.fields.CharField>', editable=False, max_length=60),
        ),
    ]
