# Generated by Django 2.2.6 on 2020-05-15 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panda', '0009_partners_slug_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partners',
            name='slug_field',
            field=models.SlugField(help_text="Generally Use 'FirstName_LastName'", max_length=60, unique=True),
        ),
    ]
