# Generated by Django 2.2.6 on 2020-05-18 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panda', '0010_auto_20200515_1606'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partners',
            name='designation',
            field=models.CharField(choices=[('Managing Partner', 'Managing Partner'), ('Senior Partner', 'Senior Partner'), ('Partner', 'Partner'), ('Principal Associate', 'Principal Associate'), ('Senior Associate', 'Senior Associate'), ('Associate', 'Associate'), ('Intern', 'Intern')], max_length=50),
        ),
    ]
